ProjetChef:
    type: entity
    table: projet_chef
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        projet:
            type: string
            nullable: false
            length: 400
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
